// Known YouTube video IDs for specific episodes, keyed by episode title
const YOUTUBE_IDS: Record<string, string> = {
  // Season 1
  'たこたこ、あがれ！': 'eWJf6luWxl8',
  '名探偵ジョージ': '8m9NPQplnRg',
  '数字あわせ': 'ZD856tODCqk',
  'アートに挑戦': 'GlE1YwWsh0c',
  'コオロギに参った': 'L_Qc4D6b6A0',
  'ワンちゃん大好き': 'JcJcH4BOxts',
  'オタマジャクシはカエルの子': 'dtfpEVTpmuE',
  '料理はサイコー': '8eQXXPzCiO8',
  'イカダにのって': 'CA9mvMnPLHw',
  'ポッポ時計': '97xY5o_Fi_U',
  'ポンプはおもい': '4O4WSBHToE0',
  'アヒルさん、いらっしゃい': 'DWAJ_2i5OTo',
  'ガラガラ、ドッカーン': 'YYmIsNNB9RI',
  '夜のどうぶつえん': 'vNCliUgO8kI',
  'ドクター・ジョージ': '56XGvmunDHE',
  'チャーキーとかくれんぼ': '4cL4NXoumwg',
  'えきちょうのジョージ': 'Rbs28gx6_uk',
  'ビーバーをたすけろ': 'VPjd02PPQPA',
  'レモネードはいかが？': 'JbYdq6MsxU4',
  '信号をまもろう': 'mqiFTe6UP44',
  'しんせつなハンドリー': 'gNDskNZpsqo',
  '白い世界へ': 'R_SB1L3I7SA',
  'ここほれワンワン': 'vKvexjeSQbU',
  'ねこちゃんどーこだ': 'B7_lceCkNUk',
  'ドーナツこわい': 'gF4m7sCQ-4c',
  'ほしいっぱい': 'AgblP8bi0dM',
  'すてきなカラーチョコ': 'tqqoti27g-g',
  'ミツバチ、ブンブン': 'FIIR5kEJUyY',
  'ジョージバーガー': 'vUVCgAksNwo',
  'おやすみジョージ': '1gG6HCHkH4I',
  'スパイ大作戦': 'vKtDkVJSug4',
  'ちいさいいけのさかな': 'XurJyyUy7fw',
  '冬ものがたり': 'PzTWZcM-UwU',
  'ハトさんのおうち': 'RpeGj1xVfpQ',
  'うきうきボート': '_H_OgosGyPI',
  'ウサギとかくれんぼ': 'sEiYgfhlNAM',
  'ドアマンはラクじゃない': 'P73tUqbW0SM',
  'たのしいキャンプ': 'ZOHjycW3Q-E',
  'ハワイへいこう': 'AvVV2cKQIX4',
  'ローラーチーム誕生': '_OUkTD0FlHQ',
  'ドングリすくすく': 'N1mV866Wcck',
  'ゴルフでホールインワン': 'dbr1ikSSVvM',
  'うなぎをたすけろ': 'e2m1s0Vg__0',
  'どろんこあそび': 'mO1CRs3eSS8',
  'まいごの２ひき': '0xsAad_TVAQ',
  'ペタペタくっつく': 'iA8h-gS5YrI',
  'うちゅうりょこう': 'PG674DmaK-k',
  'ゴールはどこだ': 'MxOoEAaWeIA',
  'レスキューモンキー': 'I23IWg9Q22o',
  'くらやみこわい': 'A3RaeRITlpU',
  'きれいなきいろいぼうし': 'rvU8ST3JDFU',
  'しんぶんでーす': '-IsbjHV3sVA',
  'めざせミュージシャン': 'I3aGKW111fQ',
  // Season 2
  'びょうきにまけるな': 'fty6O3e1lwM',
  'おしろごっこ': '5q3ZPxjIu10',
  '眠れないジョージ': 'N5zPEe6eoO0',
  'オリをやぶれ': 'bVuTpSP0Js8',
  'ユニークだぞう': 'UcbFUTpOs1U',
  'くっさーい！': 'bZ1cyBd2M8M',
  '宇宙でおしごと': 'R9Q7fieKxYI',
  '洪水だぁー': '02DEYKISpNI',
  'ゼロ ワン スリー あれ？': 'KXsq54En6fs',
  'やった・ピッタシ！': 't9KjbHsEioA',
  '春よこい': 'ws40GAUNkz0',
  'めいわくコレクション': 'qc55uLeqYVU',
  'カーテンあけて、しめて': 'LiiM-DCJiPI',
  'ゆかいなぼうし': 'nn61b7-3TUs',
  'おしごと、おしごと': 'HOCaJAU5ALQ',
  'そのゴミまったー！': 'h0ArvGrgmgs',
  'ゴロンゴロン': 'z3JGvWmzTzU',
  '見えなーい！': 'C7OiTFk-AOA',
  'チャリ～ン！': 'taqQVFyINds',
  'やった！ラッキー': 'UySM0V1_gsk',
  '妖精になりたい': 'HTCxd6QW-sc',
  'はしをわたろう': 'mW3-1s7MGlA',
  '右かな？左かな？': 'buo5OPnEAf0',
  'ゆきのくにへ': 'IFHG8H5wd58',
  'ヘビがきた！': 'Em6rPVc8mMA',
  'クモの巣がすき': 'SiMszQOvaow',
  'ともだちをたすけろ！': 'BaRE87cE6Lk',
  'ロボットを動かせ': 'RPxeQJE5fnc',
  // Season 3
  'こおりのくにでクロスカントリー': 'iJLaLDsvfMY',
  'にんじんだーいすき！': 'ajn1nWJKMH0',
  'さあ、何こだ？': 'JTQev0e1saM',
  'まっかっか': 'VLTOxnHbfX0',
  'にじのねっこ': '3rUfcxuY-fg',
  'やさいはオイシイ': 'DEVAC1xPnKE',
  'ミミズにょろにょろ': '0fHPFIvKlfE',
  'ミミズにょろにょろ（2）': 'PTEZ0GQJJA4',
  '船でぶらり旅': 'tfFdX9wJ32Q',
  'とんでけー！': 'b3uHe9k74_M',
  'プレーリードッグだよ': 'gMgEWQX0OzA',
  // Season 4
  'せんたくしよう': 'KPmExrGaRjE',
  'おてんばアリー': '8gOPLWJUnQM',
  'ハンドリーだいぼうけん': 'WeGCqqXHdYg',
  'ジョージがおおきい': 'l_pNAxcAUpM',
  'からだのなか': 'I1PIHDDlgM8',
  'リラックスはつかれる': 'xICZOtgJ1l8',
  'はこのなかのハンドリー': 'F5OAiHyYBOU',
  'はかってはかって': '5fkMlwF1_Tk',
  'りょうりをしよう': 'up1txN6ikYg',
  // Season 4+
  'ジョージオーマチック': 'ZQQaj65yrTs',
  'パレードにいこう': 'vuz4Vg8UCnw',
  'ボールのトラブル': 'BCbwwS3Vu14',
  'ジュラシックジョージ': 'd3uJwe5zDQk',
  'きたえるぞジョージ': 'xh-NLhHgQQs',
  'あたらしいなにか': 'yXGOONb5V0w',
  'ダブル・ハンドリー': 'QItbRa11r9M',
  'イエローパイレーツ': 'rdPcIynFcl8',
  'むいて、むいて、むいて': '-u5bJtzvSPI',
  'わっ、とんでる！': '0_T7KsH5OPQ',
  'リサイクルはおまかせ': 'MJPEsE9UQAY',
  'はたらけはたらけ': 'QeXYk0EZZi4',
  'おっかげろー': 'QeXYk0EZZi4',
  'ひとりオペラ': '3IQR6lj0Hkk',
  'カンガルー ピョン！': 'VS_ng3hKDFY',
  'カメレオン': 'OA9xj-tpuaA',
  'ブタのおせわ': '9bD9LX0XLQE',
  'お泊り会': 'ja-B35RvWNo',
  'ビックリ・パーティー': 'TUVcFIhGwSM',
  'ニョッキをよろこばせろ': 'weWJSaB5cn0',
  'しぼりたてジュース': 'P1VbCfLBBh4',
  'チャーキーがっこうへいく': 'dENePyPQPl8',
  'えいがかんへいこう': '5ojxYCv2LG8',
  '大きくなりたい': 'nhmXUqsIFB4',
  // Season 5
  'おおきいのはどっち？': 'RAbjXuMNbZw',
  'マルコとジョージ': 'flnuNrT-8X8',
  'ちかてつだいぼうけん': 'K8LberuwrC4',
  'よくできましたジョージ': '_HMuToNaP50',
  'ホームランをうとう': 'fJuzZawYVKA',
  'かぜのちから': 'McaqjpzoOtA',
  'ジョージのアヒルのこ': '6WQBFacT6Oc',
  'ひつじかいジョージ': 'BtKE_7lwSDc',
  'おかあさんにありがとう': 'xMwtToD-TYE',
  'そりでしゅっぱつ': 's8KBxOgXvCU',
  'きんぞくたんちき': 'rJHbwKHLVs0',
  'ほんのむし': 'SHW5lOxHYdc',
  // Season 6
  'うるさいのはコケコッコー': 'eTU9R26vGOM',
  'サル・ウィ・ダンス': 'dhv7f7z_-UU',
  'えー！ブタを１００ぴき！': 'jolv_ZHvlqI',
  'ありりりりー！': 'cH5LJyfqZPE',
  'ニョッキアルデンテ': '5GRC1Mn4aEI',
  'ぴっかぴカー': '-gsXwUtGzOU',
  'シロップコンコン': 'vtgr5YA9PAU',
  'オンエアまっさかり': '0HPUi65-tFM',
  'すなのおえかき': 'fQCMfJjjhmw',
  // Season 3
  'ゆきのなかで': 'ew9leL6ddzk',
  // Season 7
  'ハンドリーJr.': 'zgSD2nqdwd8',
  'トゥートゥートゥッツィさようなら': 'NKEsZhWjwyk',
  'かわうそだーいすっキー': 'OaguKp_g4dA',
  'ハチみつだいすき': '0yQ8SLQxYe8',
  'とんでとんで': 'eTk5jlCMx3E',
  'オー・マイ・ホーム': 'RmhPK4RB36w',
  'フルフルぼし': 'sDdbz742fs8',
  'かぜにのって': '3ihT22ou2kk',
  'おふろでナイト': 'Vby-OJ7yoqk',
  'しょうぼうたいはどこだ？': 'jmIJW5I0-ZE',
  'たまごをさがせ': 'DDS3kuCvuBw',
  'ジョージとアリーのにわ': 'mtJDKIKGNQY',
  'たからさがし': 'o2v6l8T7-DA',
  'かぜひいたジョージ': 'sHJJNP5viN0',
  // Season 8
  'おもちゃのジョージ': 'YOuCNWUEXJ0',
  'ホースダンス': 'i7e8vKZMQ84',
  'ジョージのサイフォン': 'JlRtUxfvtlM',
  'ジョージとアリーのゲーム': 'AthQOE-3D7Q',
  'ジョージのサーカス': 'WmH-xpceero',
  'あかいほしのうえで': 'FgpSk8j34xI',
  '100にいこう': 'Ywkr4QM80lg',
  'こわいものなし': 'BPrg3tJ46bc',
  // Season 9
  'ちかてつのジョージ': 'tA-RZXKU0ks',
  'アマゾンのぼうけん': 'F1aUOsjZrE4',
  'スパイジョージ': '-1rL5W7jgdw',
  'でんしゃのトラブル': 'T7mYIenutQs',
  'ボウリングをしよう': 'a7exiUYUjqc',
  'しゃしんをとろう': 'S7cHTAjG61k',
  'シカをたすけろ': 'M59EoRF7ERA',
  // Season 10
  'ジョージの新しい音': '78fvaxbqeL4',
  'ビルの車いす': '8iklRa9HLbU',
  'ドングリ泥棒': 'eeuHw3ERYqg',
  'オイルがだいかつやく': 'KhLc3NRoZUk',
  'ピクルス作り': 'Of6YOUh0LSo',
  '眠れない羊': 'eyy7UQlj6RM',
  'ハンドリーの回復': '_5Lfa8T2T58',
  'お祭りを忘れずに': 't-uopmGg11M',
  'ニッポンさるゆきがっせん': 'MdWVWUBeP5Y',
  '天体望遠鏡': '57royJvMPhc',
  'ポップコーン店番': 'wWaJCR7VhXA',
  '歯医者さん': 'gEyBw7Gfias',
  '氷の穴釣り': 'mWax_pwVwz8',
  '流れ星': 'UVNXOTVN5k4',
  'つるつるホッケー': 'jFjvSN_tld0',
  '豚の農場': 'M_mYQihcrqI',
  '羊の管理': 'QahUI5AwWNs',
  'ダックスフントを追え！': 'uQpN4lyv47E',
  '交通整理': 'xrWlm6zgTXQ',
  // Season 11
  'おとのものがたり': 'ETCRu5oWZH8',
  'ライツ！カメラ！アクション！': 'ZYskj8R5D7M',
  'すごいぞマジシャン': 'Bg8jNx_bzO8',
  'ねこのもりびと': 'SK_YbAf_5YY',
  'あらってあらって': 'WCjIDnTuHJ0',
  'そうじをしよう': 'C--yEz89EsU',
  // Season 12
  'あひるをたすけろ': '_vnqf9SWskI',
  // Season 13
  'コンパスへのものがたり': 'bnL3zbKTZu4',
  'とりのなかまたち': 'qitY9f4cLqA',
  'ジョージのちいさな図書館': '9EEGZWham9U',
  'ハムスターのおせわ': 'XXaJB6vrNEA',
  'どうくつたんけん': 'FZTWm5FKvJ0',
  'キャンプへいこう': 'tgb_3GFw-9o',
  // Various seasons
  'ドラゴンダンス': 'Bu_hD9Yz0LI',
  'あした天気になあれ': 'EQ8qTPpEUwU',
  'バレンタインデー': 'dpUiaOTSG58',
  'ネス湖の怪獣': 'mOwZPG3QPnA',
  '夜の遊園地': 'dBdUHjHpw2M',
};

export function getYouTubeId(title: string): string | null {
  return YOUTUBE_IDS[title] ?? null;
}

export function getYouTubeUrl(title: string): string {
  const id = getYouTubeId(title);
  if (id) return `https://www.youtube.com/watch?v=${id}`;
  // Fallback: search YouTube for the episode title
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(title + ' おさるのジョージ')}`;
}

export function getThumbnailUrl(title: string): string | null {
  const id = getYouTubeId(title);
  if (id) return `https://img.youtube.com/vi/${id}/hqdefault.jpg`;
  return null;
}

export function hasDirectVideo(title: string): boolean {
  return title in YOUTUBE_IDS;
}
